### ISSUE TITLE
Error while loading

### ISSUE THREAD

**Issue by SerafimArts** [lench4991/EasyScaleMod#3]
Spaar: v1.7.1
Besige: v0.45a
EasyScale: v0.6.0

![image](https://user-images.githubusercontent.com/2461257/34522951-580f26f6-f0a6-11e7-904d-40f08c3f82b6.png)

**Comment by lenartbezek** [comment]
You are using the multiverse version of EasyScale. For the old Besiege version v0.45 use this instead:
https://github.com/lench4991/EasyScaleMod/releases/tag/v1.2.2

**Comment by SerafimArts** [comment]
Since Issue was closed, then I understand that further support for the plugin for the Besiege is no longer planned?

**Comment by lenartbezek** [comment]
Support is planned to best of my abilities, but this issue is closed as the problem is simply with wrong version. If the error persists, I will reopen.
